Project.PL/Controllers/ProductController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.CodeAnalysis;
using Project.BLL.Interfaces;
using Project.DAL.Models;
using Project.PL.Helper;
using Project.PL.ViewModels;

namespace Project.PL.Controllers
{
    public class ProductController : Controller
    {
        private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;

        public ProductController(IMapper mapper,IUnitOfWork unitOfWork)
        {
            _mapper = mapper;
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index(string searchinput)
        {
            var products = Enumerable.Empty<Product>();
            if (string.IsNullOrEmpty(searchinput))
                products = _unitOfWork.ProductRepository.GetAll();

            else
                products = await _unitOfWork.ProductRepository.GetByName(searchinput.ToLower());

            var result = _mapper.Map<IEnumerable<ProductViewModel>>(products);
            return View(result);
        }

        //[HttpGet]
        //public IActionResult Create()
        //{
        //    ViewData["Customers"] = _unitOfWork.CustomerRepository.GetAll();
        //    return View();
        //}

        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult Create(ProductViewModel model)
        //{
        //    if (ModelState.IsValid)
        //    {
        //        var Product = _mapper.Map<Product>(model);
        //        _unitOfWork.ProductRepository.Add(Product);

        //        var customer = _unitOfWork.CustomerRepository.Get(Product.CustomerId.Value);
        //        customer.Salary = customer.Salary + ((int)Product.price * Product.Quantity);
        //        _unitOfWork.CustomerRepository.Update(customer);


        //        var count = _unitOfWork.Complete();
        //        if (count > 0)
        //            return RedirectToAction(nameof(Index));
        //    }
        //    return View();
        //}


        //public IActionResult Details(int? id, string viewname = "Details")
        //{
        //    ViewData["Customers"] = _unitOfWork.CustomerRepository.GetAll();

        //    if (id is null)
        //        return BadRequest();

        //    var product = _unitOfWork.ProductRepository.Get(id.Value);

        //    var ProductViewModel = _mapper.Map<ProductViewModel>(product);


        //    if (product is null)
        //        return NotFound();
        //    return View(viewname, ProductViewModel);
        //}

        //[HttpGet]
        //public IActionResult Edit(int? id)
        //{
        //    ViewData["Customers"] = _unitOfWork.CustomerRepository.GetAll();
        //    return Details(id, "Edit");
        //}


        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult Edit([FromRoute] int? id, ProductViewModel model) //to prevent any edit from anyone
        //{
        //    if (id != model.Id)
        //        return BadRequest();


        //    var product = _mapper.Map<Product>(model);


        //    if (ModelState.IsValid) // to can use data validation
        //    {
        //        var old = _unitOfWork.ProductRepository.Get(id.Value);

        //        old.price = model.price;
        //        old.priceToCST = model.priceToCST;
        //        old.CustomerId = model.CustomerId;
        //        old.Colors = model.Colors;
        //        old.description = model.description;
        //        old.name = model.name;
        //        old.Quantity = model.Quantity;
        //        old.Sizes = model.Sizes;
        //        old.Incomes=model.Incomes;

        //        var customers = _unitOfWork.CustomerRepository.GetAll();
        //        var incomes = _unitOfWork.IncomesRepository.GetAll();

        //            foreach (var cus in customers)
        //            {
        //                        cus.Salary =_unitOfWork.ProductRepository.GetAll().Where(p => p.Customer.Name == cus.Name)
        //                                    .Sum(p => p.Quantity * (int)p.price) -
        //                                    _unitOfWork.IncomesRepository.GetAll().Where(I=>I.Customer.Name ==cus.Name)
        //                                    .Sum(I=>I.IncomeAmount);
        //            _unitOfWork.CustomerRepository.Update(cus);
        //            }

        //        var count = _unitOfWork.Complete();

        //        if (count > 0)
        //        {
        //            return RedirectToAction("Index");
        //        }
        //    }
        //    return View();
        //}


        //[HttpGet]
        //public IActionResult Delete(int? id)
        //{
        //    return Details(id, "Delete");
        //}


        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public IActionResult Delete([FromRoute] int? id, ProductViewModel model) //to prevent any edit from anyone
        //{
        //    ViewData["Customers"] = _unitOfWork.CustomerRepository.GetAll();

        //    if (id != model.Id)
        //        return BadRequest();

        //    var product = _mapper.Map<Product>(model);

        //    if (ModelState.IsValid) // to can use data validation
        //    {
        //        var customer = _unitOfWork.CustomerRepository.Get(product.CustomerId.Value);
        //        customer.Salary = customer.Salary - ((int)product.price * product.Quantity);
        //        _unitOfWork.CustomerRepository.Update(customer);


        //        _unitOfWork.ProductRepository.Delete(product);
        //        var count = _unitOfWork.Complete();
        //        if (count > 0)
        //            return RedirectToAction("Index");
        //    }
        //    return View();
        //}

    }
}

Project.PL/Controllers/RoleController.cs
using Microsoft.AspNetCore.Identity;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Project.DAL.Models;
using Project.PL.ViewModels;
using Microsoft.EntityFrameworkCore;
using Project.PL.Helper;
using Microsoft.AspNetCore.Authorization;
using System.Collections.Generic;

namespace Project.PL.Controllers
{
    [Authorize]
    public class RoleController : Controller
    {
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;

        public RoleController(RoleManager<IdentityRole> roleManager,UserManager<ApplicationUser> userManager)
        {
            _roleManager = roleManager;
            _userManager = userManager;
        }



        public async Task<IActionResult> Index(string searchinput)
        {
            var roles = Enumerable.Empty<RoleViewModel>();

            if (string.IsNullOrEmpty(searchinput))
            {
                roles = await _roleManager.Roles.Select( R => new RoleViewModel()
                {
                    Id = R.Id,
                    RoleName = R.Name
                }).ToListAsync();
            }
            else
            {
                roles = await _roleManager.Roles.Where(R => R.Name
                                               .ToLower()
                                               .Contains(searchinput.ToLower()))
                                               .Select(R => new RoleViewModel
                                               {
                                                   Id = R.Id,
                                                   RoleName = R.Name
                                               }).ToListAsync();
            }

            return View(roles);
        }


        [HttpGet]
        public IActionResult create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> create(RoleViewModel model)
        {
            if (ModelState.IsValid)
            {
                var role = new IdentityRole()
                {
                    Name=model.RoleName
                };
                await _roleManager.CreateAsync(role);
                return RedirectToAction(nameof(Index));
            }
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> Details(string? id, string viewname = "Details")
        {
            if (id is null)
                return BadRequest();


            var rolefromDb = await _roleManager.FindByIdAsync(id);

            if (rolefromDb is null)
                return NotFound();

            var role = new RoleViewModel()
            {
                Id = rolefromDb.Id,
                RoleName = rolefromDb.Name
            };
            return View(viewname, role);
        }




        [HttpGet]
        public async Task<IActionResult> Edit(string? id)
        {
            return await Details(id, "Edit");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string? id, RoleViewModel model) //to prevent any edit from anyone
        {
            if (id != model.Id)
                return BadRequest();

            if (ModelState.IsValid) // to can use data validation
            {
                var rolefromDb = await _roleManager.FindByIdAsync(id);

                if (rolefromDb is null)
                    return NotFound();

                rolefromDb.Name = model.RoleName;

                var user = await _roleManager.UpdateAsync(rolefromDb);
                if (user.Succeeded)
                    return RedirectToAction(nameof(Index));
            }

            return View();
        }


        [HttpGet]
        public async Task<IActionResult> Delete(string? id)
        {
            return await Details(id, "Delete");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] string? id, RoleViewModel model) //to prevent any edit from anyone
        {
            if (id != model.Id)
                return BadRequest();

            if (ModelState.IsValid) // to can use data validation
            {
                var rolefromDb = await _roleManager.FindByIdAsync(id);

                if (rolefromDb is null)
                    return NotFound();

                rolefromDb.Name = model.RoleName;

                var user = await _roleManager.DeleteAsync(rolefromDb);
                if (user.Succeeded)
                    return RedirectToAction(nameof(Index));
            }

            return View();
        }


        [HttpGet]
        public async Task<IActionResult> AddOrRemoveUsers(string roleId)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role is null)
                return NotFound();

            ViewData["RoleId"] = roleId;

            var UserInRole = new List<UserInRoleViewModel>();
            var users = await _userManager.Users.ToListAsync();

            foreach (var user in users)
            {
                var userinrole = new UserInRoleViewModel()
                {
                    UserName = user.UserName,
                    UserId = user.Id,
                };
                if (await _userManager.IsInRoleAsync(user, role.Name))
                {
                    userinrole.IsSelected = true;
                }
                else
                {
                    userinrole.IsSelected = false;
                }
                UserInRole.Add(userinrole);
            }
            return View(UserInRole);

        }



        [HttpPost]
        public async Task<IActionResult> AddOrRemoveUsers(string roleId,List<UserInRoleViewModel> users)
        {
            var role = await _roleManager.FindByIdAsync(roleId);
            if (role is null)
                return NotFound();

            if (ModelState.IsValid)
            {
                foreach (var user in users)
                {
                    var appuser = await _userManager.FindByIdAsync(user.UserId);
                    if(appuser is not null)
                    {
                        if (user.IsSelected && ! await _userManager.IsInRoleAsync(appuser,role.Name))
                        {
                            await _userManager.AddToRoleAsync(appuser, role.Name);
                        }
                        else if (! user.IsSelected && await _userManager.IsInRoleAsync(appuser, role.Name))
                        {
                            await _userManager.RemoveFromRoleAsync(appuser, role.Name);
                        }
                    }
                    
                }
                return RedirectToAction(nameof(Edit),new { id = roleId });
            }
            return View();
        }


    }
}

Project.PL/Controllers/UserController.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Project.DAL.Models;
using Project.PL.Helper;
using Project.PL.ViewModels;

namespace Project.PL.Controllers
{
    [Authorize]

    public class UserController : Controller
	{
		private readonly UserManager<ApplicationUser> _usermanager;

		public UserController(UserManager<ApplicationUser> usermanager)
        {
			_usermanager = usermanager;
		}



		public async Task<IActionResult> Index(string searchinput)
		{
			var users = Enumerable.Empty<UserViewModel>();

			if (string.IsNullOrEmpty(searchinput))
			{
				users = await _usermanager.Users.Select(U => new UserViewModel
				{
					Id = U.Id,
					FirstName = U.FirstName,
					LastName = U.LastName,
					Email = U.Email,
					Roles = _usermanager.GetRolesAsync(U).Result
				}).ToListAsync();
			}
			else
			{
				users = await _usermanager.Users.Where(U => U.Email
											   .ToLower()
											   .Contains(searchinput.ToLower()))
											   .Select(U => new UserViewModel
											   {
												   Id = U.Id,
												   FirstName = U.FirstName,
												   LastName = U.LastName,
												   Email = U.Email,
												   Roles = _usermanager.GetRolesAsync(U).Result
											   }).ToListAsync();
			}

			return View(users);
		}


        public async Task<IActionResult> Details(string? id, string viewname = "Details")
        {
            if (id is null)
                return BadRequest();


			var userfromDb= await _usermanager.FindByIdAsync(id);

            if (userfromDb is null)
                return NotFound();

			var user = new UserViewModel()
			{
				Id = userfromDb.Id,
				FirstName = userfromDb.FirstName,
				LastName = userfromDb.LastName,
				Email = userfromDb.Email,
				Roles = _usermanager.GetRolesAsync(userfromDb).Result
			};
            return View(viewname, user);
        }




        [HttpGet]
        public async Task<IActionResult> Edit(string? id)
        {
            return await Details(id, "Edit");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string? id, UserViewModel model) //to prevent any edit from anyone
        {
            if (id != model.Id)
                return BadRequest();

                if (ModelState.IsValid) 
                {
                    var userfromDb = await _usermanager.FindByIdAsync(id);

                    if (userfromDb is null)
                        return NotFound();

                    userfromDb.FirstName = model.FirstName; 
                    userfromDb.LastName = model.LastName;
                    userfromDb.Email = model.Email;

                    var user = await _usermanager.UpdateAsync(userfromDb);
                    if (user.Succeeded)
                    return RedirectToAction(nameof(Index));
                }
           
            return View();
        }


        [HttpGet]
        public async Task<IActionResult> Delete(string? id)
        {
            return await Details(id, "Delete");
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete([FromRoute] string? id, UserViewModel model) //to prevent any edit from anyone
        {
            if (id != model.Id)
                return BadRequest();

            if (ModelState.IsValid) // to can use data validation
            {
                var userfromDb = await _usermanager.FindByIdAsync(id);

                if (userfromDb is null)
                    return NotFound();

                userfromDb.FirstName = model.FirstName;
                userfromDb.LastName = model.LastName;
                userfromDb.Email = model.Email;

                var user = await _usermanager.DeleteAsync(userfromDb);
                if (user.Succeeded)
                    return RedirectToAction(nameof(Index));
            }

            return View();
        }



    }
}

Project.PL/Views/Shared/_AuthLayout.cshtml
<!DOCTYPE html>
<html>
<head>
	<title>Creative Colorlib @ViewData["Tittle"] Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	
	<link href="~/css/AuthStyle.css" rel="stylesheet" type="text/css" media="all" />
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
</head>
<body>
	<div class="main-w3layouts wrapper">
		<h1>@ViewData["Title"] Form</h1>
		@RenderBody();
		<div class="colorlibcopy-agile">
			<p>© 2024 All rights reserved </p>
		</div>
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>

	<script src="~/lib/jquery/dist/jquery.min.js"></script>
	<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
	<script src="~/js/site.js" asp-append-version="true"></script>
	@await RenderSectionAsync("ValidationScriptSection", required: false)
</body>
</html>

Project.PL/Views/Shared/_ButtonsPartialView.cshtml
@model string

<td>
    <a asp-action="Details" asp-route-id="@Model" class="btn btn-warning">
        <i class="fas fa-eye"></i>
        Details
    </a>
</td>

<td>
    <a asp-action="Edit" asp-route-id="@Model" class="btn btn-success">
        <i class="fas fa-eye"></i>
        Update
    </a>
</td>

<td>
    <a asp-action="Delete" asp-route-id="@Model" class="btn btn-danger">
        <i class="fas fa-eye"></i>
        Delete
    </a>
</td>

Project.PL/Views/Shared/_INDPRO.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Products Catalog @ViewData["Tittle"] Form</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link href="~/css/productIn.css" rel="stylesheet" type="text/css" media="all" />
</head>
<body>
    <header>
        <nav class="navbar">
            <div class="logo">
                <a href="/">Product Catalog</a>
            </div>


            <div class="nav-links">
                    <a class="nav-link text-light ">Electronics</a>
            </div>

            <div class="nav-links">
                <a class="nav-link text-light ">Phones</a>
            </div>

            <div class="nav-links">
                <a class="nav-link text-light ">Home</a>
            </div>

            <div class="nav-links">
                <a class="nav-link text-light ">Kitchen</a>
            </div>

            <div class="nav-links">
                <a class="nav-link text-light ">Cloths</a>
            </div>

            <div class="nav-links">
                <a class="nav-link text-light ">Sports</a>
            </div>

            <div class="nav-links">
                <a class="nav-link text-light ">Books</a>
            </div>

            <div class="nav-links">
                <a class="nav-link text-light ">VideoGames</a>
            </div>

            @if (User.IsInRole("Admin"))
            {
                <div class="nav-item">
                    <a class="nav-link text-light btn btn-info" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                </div>

                <div class="nav-item">
                    <a class="nav-link text-light btn btn-info" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
            </div>
            }
            <div class="nav-item">
                <a class="nav-link text-light ">Welcome @User.Identity.Name</a>
            </div>

            <div class="nav-item">
                <a class="nav-link text-light btn btn-danger float-left" asp-area="" asp-controller="Account" asp-action="SignOut">Sign Out</a>
            </div>
            
        </nav>
    </header>

    @RenderBody();



    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("ValidationScriptSection", required: false)
</body>
</html>

Project.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Project.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">


                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                    <img src="~/Files/Images/logo.jpg" width="75" class="img-fluid" />
                </a>

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Products</a>
                        </li>
                    </ul>

                    <ul class="nav navbar-nav navbar-right">
                        
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                        </li>

                        <li class="nav-item">
                            <a class="nav-link text-light btn btn-danger float-left" asp-area="" asp-controller="Account" asp-action="SignOut">SignOut</a>
                        </li>


                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Project.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("ValidationScriptSection", required: false)
</body>
</html>